Updates based on the comments. Using 'mvn clean install -DskipTests' to skip the tests when building ion-java. Update the output of version-number-check. Update the trigger event of prerelease creating workflow and add one step to check the version number.

diff --git a/.github/workflows/version-bump-and-fast-forward-check.yml b/.github/workflows/version-bump-and-fast-forward-check.yml
--- a/.github/workflows/version-bump-and-fast-forward-check.yml
+++ b/.github/workflows/version-bump-and-fast-forward-check.yml
@@ -5,6 +5,8 @@ jobs:
   check-version-bump:
     name: check-version-bump
     runs-on: ubuntu-latest
+    outputs:
+      output1: ${{ steps.check-version-change.outputs.result }}
     steps:
       - name: Switch to the branch of the pull request
         uses: actions/checkout@v3
@@ -20,31 +22,19 @@ jobs:
           path: ion-java-current
 
       - name: Check whether the pull request contains version number bump
+        id: check-version-change
         run: |
           cd /home/runner/work/ion-java/ion-java/ion-java-new
           versionNew=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
           commitID=$(git rev-parse HEAD)
           cd /home/runner/work/ion-java/ion-java/ion-java-current
           versionCurrent=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
-          if [[ $versionNew != $versionCurrent ]]; then echo "version bump check pass"; else exit 1; fi 
-
-  comment-when-version-number-check-failed:
-    needs: check-version-bump
-    if: ${{ failure() }}
-    runs-on: ubuntu-latest
-    name: comment-when-version-number-check-failed
-    steps:
-      - name: Create comment
-        uses: peter-evans/create-or-update-comment@v2
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          body: |
-            This PR doesn't contain version number bump and will not trigger the ion-java GitHub prerelease process.
+          if [[ $versionNew != $versionCurrent ]]; then echo "::set-output name=result::pass"; else echo "::set-output name=result::failed"; fi
 
   fast-forward-check:
     needs: check-version-bump
     name: fast-forward-check
-    if: ${{ success() }}
+    if: ${{ needs.check-version-bump.outputs.output1 == 'pass' }}
     runs-on: ubuntu-latest
     steps:
       - name: Access to the last release
@@ -82,7 +72,7 @@ jobs:
       - name: Check whether the incoming release is fast-forward compared to the last release
         run: |
           cd ion-java-new 
-          if git merge-base --is-ancestor ${{env.current_release_commit_id}} ${{env.current_release_commit_id}}; then echo "Trigger github release"; else exit 1; fi 
+          if git merge-base --is-ancestor ${{env.last_release_commit_id}} ${{env.current_release_commit_id}}; then echo "Trigger github release"; else exit 1; fi
 
       - name: comment
         if: steps.build.outputs.exit_code == 0
@@ -90,7 +80,7 @@ jobs:
         with:
           issue-number: ${{ github.event.pull_request.number }}
           body: |
-            This PR passes version bump check and fast-forward check, please double check the version number and merge this PR. After merging this PR, please trigger "Create gitHub prerelease after fast-forward check" workflow manually to create prerelease.
+            This PR passes version bump check and fast-forward check, please double check the version number and merge this PR. After merging this PR, "Create gitHub prerelease after fast-forward check" workflow will be automatically triggered to create prerelease.
 
       - name: comment
         if: steps.build.outputs.exit_code == 1
